name: fno_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - bottleneck=1.4.2=py311haa0f9ac_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - comm=0.2.3=pyhe01879c_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py311hbdd6827_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py311hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.4=h77a78f3_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnsl=2.0.0=h5eee18b_0
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h2ed474d_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-base=3.10.6=py311h71dd3da_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py311hacdc0fc_0
  - mkl_fft=2.1.1=py311h8fe796d_0
  - mkl_random=1.3.0=py311h505adc9_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.11.0=py311h397f862_1
  - numpy-base=2.3.4=py311h6ab9638_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h505adc9_0
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311hb1c3d2d_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py311hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py311h06a4308_0
  - pyzmq=27.1.0=py311hcf8288c_0
  - readline=8.3=hc2a1206_0
  - seaborn=0.13.2=py311h06a4308_3
  - setuptools=80.9.0=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
    - annotated-types==0.7.0
    - certifi==2025.10.5
    - charset-normalizer==3.4.4
    - click==8.3.0
    - configmypy==0.2.0
    - contourpy==1.3.3
    - crc32c==2.8
    - cycler==0.12.1
    - donfig==0.8.1.post1
    - filelock==3.19.1
    - fsspec==2025.9.0
    - gitdb==4.0.12
    - gitpython==3.1.45
    - h5py==3.15.1
    - idna==3.11
    - iniconfig==2.3.0
    - jinja2==3.1.6
    - kiwisolver==1.4.9
    - markupsafe==2.1.5
    - matplotlib==3.10.7
    - mpmath==1.3.0
    - networkx==3.5
    - neuraloperator==2.0.0
    - numcodecs==0.16.3
    - numpy==2.3.3
    - nvidia-cublas-cu12==12.6.4.1
    - nvidia-cuda-cupti-cu12==12.6.80
    - nvidia-cuda-nvrtc-cu12==12.6.77
    - nvidia-cuda-runtime-cu12==12.6.77
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.0.4
    - nvidia-cufile-cu12==1.11.1.6
    - nvidia-curand-cu12==10.3.7.77
    - nvidia-cusolver-cu12==11.7.1.2
    - nvidia-cusparse-cu12==12.5.4.2
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.6.85
    - nvidia-nvshmem-cu12==3.3.20
    - nvidia-nvtx-cu12==12.6.77
    - opt-einsum==3.4.0
    - pluggy==1.6.0
    - protobuf==6.33.0
    - pydantic==2.12.3
    - pydantic-core==2.41.4
    - pyparsing==3.2.5
    - pytest==8.4.2
    - pytest-mock==3.15.1
    - pyyaml==6.0.3
    - requests==2.32.5
    - ruamel-yaml==0.18.16
    - ruamel-yaml-clib==0.2.14
    - scipy==1.16.3
    - sentry-sdk==2.43.0
    - smmap==5.0.2
    - sympy==1.14.0
    - tensorly==0.9.0
    - tensorly-torch==0.5.0
    - torch==2.9.0+cu126
    - torch-harmonics==0.8.0
    - torchvision==0.24.0+cu126
    - triton==3.5.0
    - typing-inspection==0.4.2
    - urllib3==2.5.0
    - wandb==0.22.3
    - zarr==3.1.3
    - zencfg==0.6.0
prefix: /home/prad/.conda/envs/fno_env
